spring:
  application:
    name: eureka-client
server:
  port: 8083
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true